name: OOM Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Show environment
        shell: powershell
        run: |
          wsl.exe -d Ubuntu --exec /usr/bin/env -i HOME=/home/yutaro USER=yutaro PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /bin/bash --noprofile --norc -c "uname -a && cd ~/src/oom-build-tools && pwd"

      - name: Pull latest scripts repo
        shell: powershell
        run: |
          wsl.exe -d Ubuntu --exec /usr/bin/env -i HOME=/home/yutaro USER=yutaro PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /bin/bash --noprofile --norc -c "cd ~/src/oom-build-tools && git pull --ff-only"

      - name: Run OOM Android build
        shell: powershell
        run: |
          wsl.exe -d Ubuntu --exec /usr/bin/env -i HOME=/home/yutaro USER=yutaro PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /bin/bash --noprofile --norc -c "cd ~/src/oom-build-tools && ./oom-run.sh"
